on: push
# jobs:
#   job1:
#     runs-on: ubuntu-latest
#     steps:
#     - run: pwd
#     - run: ls
#   job2:
#     runs-on: windows-latest
#     steps:
#     - run: node --version
#     - run: npm run build
    
jobs:
  npm-build:
    name: npm-build工作
    runs-on: ubuntu-latest
    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4

    - name: 安装pnpm
      run: npm install pnpm -g

    - name: 跳到main目录
      run: cd ./app/main

    - name: 安装依赖
      run: pnpm install

    - name: 打包项目
      run: pnpm run build
    
    
    
  
