on: push
# jobs:
#   job1:
#     runs-on: ubuntu-latest
#     steps:
#     - run: pwd
#     - run: ls
#   job2:
#     runs-on: windows-latest
#     steps:
#     - run: node --version
#     - run: npm run build
    
jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
    - run: pwd
    - run: npm --version
    - run: npm install
    - run: npm run build
    
    
    
  
