name: 打包VUE项目
on: push

permissions:
  contents: write
# jobs:
#   job1:
#     runs-on: ubuntu-latest
#     steps:
#     - run: pwd
#     - run: ls
#   job2:
#     runs-on: windows-latest
#     steps:
#     - run: node --version
#     - run: npm run build
    
jobs:
  npm-build:
    name: npm-build工作
    runs-on: ubuntu-latest
    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4

    - name: 安装pnpm && 安装依赖 && 打包依赖
      run: npm install pnpm -g && cd ./app/main && pnpm install && pnpm run build
        
    - name: 部署
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: ./app/main/dist

    
    
    
  
